//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicEventDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ImagePath { get; set; }
        public string PhoneNo { get; set; }
        public string Discription { get; set; }
        public string Discount { get; set; }
        public string Address { get; set; }
        public bool IsActive { get; set; }
        public string URL { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public bool IsGlobal { get; set; }
    }
}
