//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicEventDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupChat
    {
        public long ChatID { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string Chattext { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> ISDeleted { get; set; }
        public Nullable<int> EventID { get; set; }
        public bool IsEvent { get; set; }
    }
}
