//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicEventDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long LogsID { get; set; }
        public string Messages { get; set; }
        public int TemplateID { get; set; }
        public int UserID { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public string test { get; set; }
    }
}
