//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicEventDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubEvent
    {
        public int SubEventID { get; set; }
        public int EventID { get; set; }
        public string SubEventName { get; set; }
        public string SubEventDiscription { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> SubStartDate { get; set; }
        public Nullable<System.DateTime> SubEndDate { get; set; }
        public Nullable<System.TimeSpan> SubStartTime { get; set; }
        public Nullable<System.TimeSpan> SubEndTime { get; set; }
        public string Image { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public Nullable<bool> ISActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public Nullable<System.DateTime> UpdatedDatetime { get; set; }
    }
}
